### ISSUE TITLE
Failed to decode downloaded font, again

### ISSUE THREAD

**Issue by jimbojetlag** [preboot/angular-webpack#78]
The fix of #59 still does not work, try this:

``` css
@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: url(/fonts/MaterialIcons.woff) format('woff');
}
```

This will only work with `url(http://localhost:8080/fonts/MaterialIcons.woff)`, and hardcoding the dev host is a bad idea.
